### ISSUE TITLE
Random failures when forking a process

### ISSUE THREAD

**Issue by srjlewis** [couchbase/couchbase-php-client#194]
Hi

I am getting random failures when forking a process.

It shows as a `Couchbase\Exception\AmbiguousTimeoutException` or a `Couchbase\Exception\UnambiguousTimeoutException` in the client or parent.

The test script being used is [here](https://github.com/srjlewis/couchbase-forking-error/blob/main/simple-tests.php)

This is a example of a parent failing [link](https://github.com/srjlewis/couchbase-forking-error/actions/runs/12083462409/job/33696634110)

Most of the other workflow jobs are showing child failures [link](https://github.com/srjlewis/couchbase-forking-error/actions/runs/12083462409)

The tests are using the following matrix
```yml
 matrix:
  operating-system: [ubuntu-latest]
  php-versions: ['8.3', '8.4']
  ext-versions: ['couchbase-4.2.2', 'couchbase-4.2.3', 'couchbase-4.2.4', 'couchbase']
```

I am also seing it fail on MacOS aarch64
